name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 */8 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACCOUNT2: ${{ secrets.ACCOUNT2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
          ACCOUNT3: ${{ secrets.ACCOUNT3 }}
          PASSWORD3: ${{ secrets.PASSWORD3 }}
          ACCOUNT4: ${{ secrets.ACCOUNT4 }}
          PASSWORD4: ${{ secrets.PASSWORD4 }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD} ${EAI_SESS}
          python3 clock-in.py ${ACCOUNT2} ${PASSWORD2} ${EAI_SESS}
          python3 clock-in.py ${ACCOUNT3} ${PASSWORD3} ${EAI_SESS}
          python3 clock-in.py ${ACCOUNT4} ${PASSWORD4} ${EAI_SESS}
